ip_source: "fixed"
# Erlaubte Werte: "json", "fixed", "domain"

# Bei ip_source: "json"
json_url: "https://json.extendsclass.com/bin/948068a1fd08"
json_field: "ip"

# Bei ip_source: "fixed"
fixed_ip: "Noch keine ip eingetragen"

# Bei ip_source: "domain"
domain: ""
